### ISSUE TITLE
Question: What are profiles? How do they differ from workspaces?

### ISSUE THREAD

**Issue by Sighery** [JonnyHaystack/i3-resurrect#116]
I tried looking at the README, reading issues that mention profiles and looking at the code in `layout.py`,  but I can't quite figure it out. I initially thought profiles were a combination of workspaces, so you could save multiple workspaces under a profile, and then restore the whole profile. However, it doesn't seem like this is the case? If I try something like `i3-resurrect save -w 1 -w 2 -w 3 -w 9 -p work`, it will just save workspace 9 to the profile (my guess is the other workspaces also get stored, but they are all stored to the same file so the last workspace overwrites).

**Comment by JonnyHaystack** [comment]
A profile basically just saves a single workspace to a specific named file. So instead of being a specific workspace number slot, you can restore it wherever you want. I made a rofi script that uses this. Personally I use that for saving a workspace setup that I'm going to need in future but might be using that workspace for something else until then, and don't want to lose the workspace.

If you want to save multiple workspaces as a separate set from the default, you can use the `-d` or `--directory` option to set a different base directory.

**Comment by Sighery** [comment]
Got it. Then yeah, mistake on my part. I thought profiles were groups of workspaces, rather than storing a workspace under a different name.

Thanks for the quick answer!
