### ISSUE TITLE
Can't install `yay -S i3-resurrect-git` in manjaro

### ISSUE THREAD

**Issue by jakob1379** [JonnyHaystack/i3-resurrect#72]
**Describe the bug**
I3-resurrect can't be installed via yay as it depends on yet unreleased python-i3ipc

**To Reproduce**
1. open terminel
2. yay -S i3-resurrect-git`
3. See error

**Expected behavior**
1. open terminel
2. yay -S i3-resurrect-git`
3. Program installs

**Additional context**
though python-i3ipc does not exist on yay just yet, the library `aur/i3ipc-python-git` should do just fine and which is installed and can be used as `import i3ipc`.

**Note**
Works if I just clone and use `python setup.py install`

**Comment by JonnyHaystack** [comment]
It was using i3ipc-python-git until the 1.4.0 release a couple days ago, but I saw it was released in the official Arch repos so I changed it to use that one. Shouldn't it be in the official Manjaro repos within a week or two?

**Comment by jakob1379** [comment]
I have no clue how the procedure for the Manjaro repos work, whether it is automated or developers have to add their software themself :/

**Comment by JonnyHaystack** [comment]
From what I understand, Manjaro's repos are just Arch but about 2 weeks delayed. This package came out in Arch repos just over a week ago so it should be in Manjaro's repos within a week.

Manjaro make it clear that they can't fully support the AUR because packages are out of sync. It's something of a hack to even use it in Manjaro. It's the AUR not the MUR after all :smile:

Seeing as you are able to install through pip or directly use setuptools, and that this should resolve itself in a few days anyway, I don't see much point in changing the package for a few days just to change it back again. However, I will try to avoid such circumstances in the future where possible.

**Comment by jakob1379** [comment]
I guess. I Just wondered if it had something to do with how the python packages are checked from your side. But how you describe it seems to indicate that it is a problem with pacman, since yay basically is just an interface to the AUR via pacman.

**Comment by JonnyHaystack** [comment]
I switched back to i3ipc-python-git to fix #74 so this should be fixed now even if the package has not yet reached Manjaro's repos.
