### ISSUE TITLE
restoring would get mixed up if the commands are run without delay

### ISSUE THREAD

**Issue by pvonmoradi** [JonnyHaystack/i3-resurrect#95]
I've written a bash script to restore a number of my workspaces. If I execute the script, some of the programs in a workspace would get sucked into another workspace. This behavior does not occur if there is a delay involved.
```bash
#!/bin/bash

i3-resurrect restore -w 1 -d ~/.i3/i3-resurrect/project-name/ --programs-only
sleep 1
i3-resurrect restore -w 2 -d ~/.i3/i3-resurrect/project-name/
sleep 1
i3-resurrect restore -w 3 -d ~/.i3/i3-resurrect/project-name/
sleep 1
i3-resurrect restore -w 4 -d ~/.i3/i3-resurrect/project-name/
sleep 1
i3-resurrect restore -w 9 -d ~/.i3/i3-resurrect/project-name/
```
**To Reproduce**
If I omit the "delay"s , a terminal in w2 would get spawned in w3.

**System information (please complete the following information):**
 - Linux distribution: Xubuntu 18.04
 - i3-resurrect version (output of `i3-resurrect --version`): 1.4.3
 - i3 version (output of `i3 -v`): 4.18.2 (2020-07-26)
 - Python version (output of `python -V`): 3.8.2

**Additional context**
I'm also using i3-focus-last and i3-auto-orientation scripts.

**Comment by JonnyHaystack** [comment]
If I understand your problem correctly this isn't really a bug as we cannot guarantee when the program will finish starting. The best way is to restore layouts in all workspaces first, then restore all the programs afterwards. I should probably make it so layout is restored before programs if neither `--layout-only` nor `--programs-only` are used. You could try editing `~/.local/lib/python3.8/site-packages/i3_resurrect/main.py` to do that yourself and see if it fixes your problem.

**Comment by pvonmoradi** [comment]
@JonnyHaystack 
Thanks. Yeah, I was including title: `i3-resurrect save -w 1 --swallow=class,instance,title -d ~/.i3/i3-resurrect/project-name/ `
I'm using pipx to install your script. I'll see if I can modify it (because it will change some hashes and pipx may complain)
So this was expected behavior. 👍

**Comment by pvonmoradi** [comment]
FWIW, this didn't work. The problem became worse cause *all* terminals were spawned in a workspace
```bash
#!/bin/bash

i3-resurrect restore -w 1 -d ~/.i3/i3-resurrect/project-name/ --programs-only

i3-resurrect restore -w 2 -d ~/.i3/i3-resurrect/project-name/ --layout-only
i3-resurrect restore -w 3 -d ~/.i3/i3-resurrect/project-name/ --layout-only
i3-resurrect restore -w 4 -d ~/.i3/i3-resurrect/project-name/ --layout-only
i3-resurrect restore -w 9 -d ~/.i3/i3-resurrect/project-name/ --layout-only

i3-resurrect restore -w 2 -d ~/.i3/i3-resurrect/project-name/ --programs-only
i3-resurrect restore -w 3 -d ~/.i3/i3-resurrect/project-name/ --programs-only
i3-resurrect restore -w 4 -d ~/.i3/i3-resurrect/project-name/ --programs-only
i3-resurrect restore -w 9 -d ~/.i3/i3-resurrect/project-name/ --programs-only
```

**Comment by JonnyHaystack** [comment]
Oh wait, ignore the thing about modifying it. It already does restore the layout first. I read my own code wrong :sweat_smile:

I think the only reliable way to restore multiple workspaces is to restore the layout for all workspaces first, and only then restore programs. This is something I do personally, but I do it with the example keybindings shown in the README. I enter restore mode and use mod+<workspace number> to restore the layouts of several workspaces, then <workspace number> to restore the programs which should get swallowed into the correct place regardless of what workspace they're launched on. This may not always work perfectly due to some bugs in i3, but when it fails I would usually just reapply the layout to fix it.

**Comment by pvonmoradi** [comment]
@JonnyHaystack But in my latest script, I restored the layouts for all workspaces first, then ran the programs.

**Comment by JonnyHaystack** [comment]
Yeah, sorry, I started writing before you sent your message. Does it work if you manually run those commands one at a time? Or put a delay only for certain parts? If you could fix it with a delay that is not in the program startup bit that would be good, because the layout restoring takes a much more predictable amount of time than starting programs does.

As you can see, this is all pretty hacky, which is another reason why I'm not excited to add an `--all` flag. I can't do this in Python in any better way than it can be done in bash, so it will be an unreliable feature that people will report bugs for when it doesn't work for them. Also it's cleaner and less code to do in bash as well.. :-/

**Comment by pvonmoradi** [comment]
@JonnyHaystack Yeah I'm ok with the `sleep 1`s :D
Thanks anyway.
